
@rootUrl=http://localhost:3034


### chatelet+les+halles
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles/auber

### st+germain+en+laye
GET {{rootUrl}}/next-trains/rers/A/st+germain+en+laye/auber

### st+germain+en+laye
GET {{rootUrl}}/next-trains/rers/A/st+germain+en+laye/auber

### le+vesinet+le+pecq
GET {{rootUrl}}/next-trains/rers/A/le+vesinet+le+pecq/auber

### houilles - (not supported - SNCF)
GET {{rootUrl}}/next-trains/rers/A/houilles/auber

### boissy+saint+leger
GET {{rootUrl}}/next-trains/rers/A/boissy+saint+leger/auber