
@rootApiUrl=https://api-ratp.pierre-grimaud.fr/v4

### Current departure at chatelet+les+halles
{{rootApiUrl}}/schedules/rers/a/chatelet+les+halles/A+R

### Current departure at neuville+universite
{{rootApiUrl}}/schedules/rers/a/neuville+universite/A+R

### Current departure at st+germain+en+laye
{{rootApiUrl}}/schedules/rers/a/st+germain+en+laye/A+R

### Current departure at boissy+saint+leger
{{rootApiUrl}}/schedules/rers/a/boissy+saint+leger/A+R

### Current departure at le+vesinet+le+pecq
{{rootApiUrl}}/schedules/rers/a/le+vesinet+le+pecq/A+R

### Current departure at nanterre+ville
{{rootApiUrl}}/schedules/rers/a/nanterre+ville/A+R

### Current departure at nanterre+prefecture
{{rootApiUrl}}/schedules/rers/a/nanterre+prefecture/A+R

### Mission ZUMO
{{rootApiUrl}}/missions/rers/A/ZUMO

### Mission UZEL
https://api-ratp.pierre-grimaud.fr/v4/missions/rers/A/UZEL

### Mission TOZZ (invalid but served in schedule)
https://api-ratp.pierre-grimaud.fr/v4/missions/rers/A/TOZZ
