
@rootApiUrl=https://api-ratp.pierre-grimaud.fr/v4

### Current departure at chatelet+les+halles
{{rootApiUrl}}/schedules/rers/a/chatelet+les+halles/A+R

### Current departure at neuville+universite
{{rootApiUrl}}/schedules/rers/a/neuville+universite/A+R

### Current departure at st+germain+en+laye
{{rootApiUrl}}/schedules/rers/a/st+germain+en+laye/A+R

### Current departure at boissy+saint+leger
{{rootApiUrl}}/schedules/rers/a/boissy+saint+leger/A+R
