
@rootUrl=http://localhost:3034

### ping
GET {{rootUrl}}/

### error-async
GET {{rootUrl}}/error-async

### error-sync
GET {{rootUrl}}/error-sync

### error-validation
GET {{rootUrl}}/error-validation

### error-server-unavailable
GET {{rootUrl}}/error-server-unavailable