
@rootUrl=http://localhost:3034

### chatelet+les+halles - RATP
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles/auber

### st+germain+en+laye - RATP
GET {{rootUrl}}/next-trains/rers/A/st+germain+en+laye/auber

### le+vesinet+le+pecq - RATP
GET {{rootUrl}}/next-trains/rers/A/le+vesinet+le+pecq/auber

### cergy+le+haut - SNCF
GET {{rootUrl}}/next-trains/rers/A/cergy+le+haut/auber

### cergy+st+christophe - SNCF
GET {{rootUrl}}/next-trains/rers/A/cergy+st+christophe/auber

### neuville+universite - SNCF
GET {{rootUrl}}/next-trains/rers/A/neuville+universite/auber

### conflans+fin+d'oise - SNCF
GET {{rootUrl}}/next-trains/rers/A/conflans+fin+d'oise/auber

### acheres+ville - SNCF
GET {{rootUrl}}/next-trains/rers/A/acheres+ville/auber

### maisons+laffitte - SNCF
GET {{rootUrl}}/next-trains/rers/A/maisons+laffitte/auber

### sartrouville - SNCF
GET {{rootUrl}}/next-trains/rers/A/sartrouville/auber

### houilles - SNCF
GET {{rootUrl}}/next-trains/rers/A/houilles/auber

### nanterre+prefecture - RATP
GET {{rootUrl}}/next-trains/rers/A/nanterre+prefecture/auber

### grande+arche+la+defense - RATP
GET {{rootUrl}}/next-trains/rers/A/grande+arche+la+defense/auber

### charles+de+gaulle+etoile - RATP
GET {{rootUrl}}/next-trains/rers/A/charles+de+gaulle+etoile/auber

### auber - RATP
GET {{rootUrl}}/next-trains/rers/A/auber/chatelet+les+halles

### chatelet+les+halles - RATP
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles/auber

### gare+de+lyon - RATP
GET {{rootUrl}}/next-trains/rers/A/gare+de+lyon/auber

### nation - RATP
GET {{rootUrl}}/next-trains/rers/A/nation/auber

### vincennes - RATP
GET {{rootUrl}}/next-trains/rers/A/vincennes/auber

### fontenay+sous+bois - RATP
GET {{rootUrl}}/next-trains/rers/A/fontenay+sous+bois/auber

### nogent+sur+marne - RATP
GET {{rootUrl}}/next-trains/rers/A/nogent+sur+marne/auber

### joinville+le+pont - RATP
GET {{rootUrl}}/next-trains/rers/A/joinville+le+pont/auber

### saint+maur+creteil - RATP
GET {{rootUrl}}/next-trains/rers/A/saint+maur+creteil/auber

### le+parc+de+saint+maur - RATP
GET {{rootUrl}}/next-trains/rers/A/le+parc+de+saint+maur/auber

### champigny - RATP
GET {{rootUrl}}/next-trains/rers/A/champigny/auber

### la+varenne+chennevieres - RATP
GET {{rootUrl}}/next-trains/rers/A/la+varenne+chennevieres/auber

### sucy+bonneuil - RATP
GET {{rootUrl}}/next-trains/rers/A/sucy+bonneuil/auber

### cergy+prefecture - SNCF
GET {{rootUrl}}/next-trains/rers/A/cergy+prefecture/auber

### boissy+saint+leger - RATP
GET {{rootUrl}}/next-trains/rers/A/boissy+saint+leger/auber
