
@rootUrl=http://localhost:3034

### all missions at chatelet+les+halles
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles

### st+germain+en+laye
GET {{rootUrl}}/next-trains/rers/A/st+germain+en+laye

### le+vesinet+le+pecq
GET {{rootUrl}}/next-trains/rers/A/le+vesinet+le+pecq

### cergy+le+haut
GET {{rootUrl}}/next-trains/rers/A/cergy+le+haut

### cergy+st+christophe
GET {{rootUrl}}/next-trains/rers/A/cergy+st+christophe

### neuville+universite
GET {{rootUrl}}/next-trains/rers/A/neuville+universite

### conflans+fin+d'oise
GET {{rootUrl}}/next-trains/rers/A/conflans+fin+d'oise

### acheres+ville
GET {{rootUrl}}/next-trains/rers/A/acheres+ville

### maisons+laffitte
GET {{rootUrl}}/next-trains/rers/A/maisons+laffitte

### sartrouville
GET {{rootUrl}}/next-trains/rers/A/sartrouville

### houilles
GET {{rootUrl}}/next-trains/rers/A/houilles

### nanterre+prefecture
GET {{rootUrl}}/next-trains/rers/A/nanterre+prefecture

### grande+arche+la+defense
GET {{rootUrl}}/next-trains/rers/A/grande+arche+la+defense

### charles+de+gaulle+etoile
GET {{rootUrl}}/next-trains/rers/A/charles+de+gaulle+etoile

### auber
GET {{rootUrl}}/next-trains/rers/A/auber

### chatelet+les+halles
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles

### gare+de+lyon
GET {{rootUrl}}/next-trains/rers/A/gare+de+lyon

### nation
GET {{rootUrl}}/next-trains/rers/A/nation

### vincennes
GET {{rootUrl}}/next-trains/rers/A/vincennes

### fontenay+sous+bois
GET {{rootUrl}}/next-trains/rers/A/fontenay+sous+bois

### nogent+sur+marne
GET {{rootUrl}}/next-trains/rers/A/nogent+sur+marne

### joinville+le+pont
GET {{rootUrl}}/next-trains/rers/A/joinville+le+pont

### saint+maur+creteil
GET {{rootUrl}}/next-trains/rers/A/saint+maur+creteil

### le+parc+de+saint+maur
GET {{rootUrl}}/next-trains/rers/A/le+parc+de+saint+maur

### champigny
GET {{rootUrl}}/next-trains/rers/A/champigny

### la+varenne+chennevieres
GET {{rootUrl}}/next-trains/rers/A/la+varenne+chennevieres

### sucy+bonneuil
GET {{rootUrl}}/next-trains/rers/A/sucy+bonneuil

### cergy+prefecture
GET {{rootUrl}}/next-trains/rers/A/cergy+prefecture

### acheres+ville
GET {{rootUrl}}/next-trains/rers/A/acheres+ville

### sartrouville
GET {{rootUrl}}/next-trains/rers/A/sartrouville

### houilles
GET {{rootUrl}}/next-trains/rers/A/houilles

### boissy+saint+leger
GET {{rootUrl}}/next-trains/rers/A/boissy+saint+leger

### boissy+saint+leger
GET {{rootUrl}}/next-trains/rers/A/boissy+saint+leger