
@rootUrl=http://localhost:3034

### all missions at chatelet+les+halles
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles

### missions TAXE at chatelet+les+halles
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles?missions=TAXE

### missions TAXE and NOTE at chatelet+les+halles
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles?missions=TAXE,NOTE

### st+germain+en+laye
GET {{rootUrl}}/next-trains/rers/A/st+germain+en+laye

### st+germain+en+laye
GET {{rootUrl}}/next-trains/rers/A/st+germain+en+laye?missions=QIKI

### le+vesinet+le+pecq
GET {{rootUrl}}/next-trains/rers/A/le+vesinet+le+pecq?missions=QIKI