
@rootUrl=http://localhost:3034

### all missions at chatelet+les+halles
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles

### missions TAXE at chatelet+les+halles
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles?missions=TAXE

### missions TAXE and NOTE at chatelet+les+halles
GET {{rootUrl}}/next-trains/rers/A/chatelet+les+halles?missions=TAXE+NOTE