
@rootUrl=http://localhost:3034

### all stations

GET {{rootUrl}}/schedules

### Station only

GET {{rootUrl}}/schedules/maisons-laffitte


### Station + direction
GET {{rootUrl}}/schedules/saint-germain-en-laye/le-vesinet-centre

### Station + direction
GET {{rootUrl}}/schedules/maisons-laffitte/cergy-le-haut

### Station + direction
GET {{rootUrl}}/schedules/maisons-laffitte/marne-la-vallee-chessy

### Validation error
GET {{rootUrl}}/schedules/invalid-station

### Connectivity error .. TODO
GET {{rootUrl}}/schedules/maisons-laffitte