# On commit this workflow will run tests

name: check-live

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: Install dependencies
        run: npm ci

      - name: Run live tests
        run: npm run ci:test-live
        env:
          CI: true
